const places = [
  // {
  //   id: 0,
  //   name: "Our Favorite Place",
  //   location: "BXSea, Tangerang Selatan",
  //   date: "",
  //   note: 'That scene where Oliver says, “Ask me how deep the ocean is,” always drifts back to me whenever we’re here.',
  //   emoji: "🐟",
  //   color: "#f4a0bc",
  //   lat: -6.28532055646212,
  //   lng: 106.72888595383031,
  //   media: [
  //     { type: "image", src: "rsc/img/dummy.png" },
  //     { type: "video", src: "rsc/vid/dummy.mp4" },
  //   ],
  // },
  {
    id: 1,
    name: "The Beginning Of Our Journey To Explore Aqurium",
    location: "Jakarta Aquarium, Jakarta",
    date: "",
    note: 'Full of life, cheerful, and pretty but I think I’m not really talking about the place. It’s the person that goes there with me.',
    emoji: "🐟",
    color: "#f4a0bc",
    lat: -6.174654779029025,
    lng: 106.78995684010924,
    media: [
      { type: "image", src: "rsc/img/jkt-aq/1.png" },
      { type: "image", src: "rsc/img/jkt-aq/2.png" },
      { type: "image", src: "rsc/img/jkt-aq/3.png" },
      { type: "image", src: "rsc/img/jkt-aq/4.png" },
      { type: "video", src: "rsc/vid/jkt-aq/1.mp4" },
    ],
  },
  {
    id: 2,
    name: "Our (Temporary) Home",
    location: "Aparatement Pancoran Riverside, Jakarta",
    date: "",
    note: "If there were a way to remain in a single moment forever, I would always choose this one",
    emoji: "🏠",
    color: "#f472a8",
    lat: -6.251301118150136,
    lng: 106.86168926683312,
    media: [
      { type: "image", src: "rsc/img/apt/1.png" },
      { type: "image", src: "rsc/img/apt/2.png" },
      { type: "image", src: "rsc/img/apt/3.png" },
      { type: "image", src: "rsc/img/apt/4.png" },
      { type: "video", src: "rsc/vid/apt/1.mp4" },
    ],
  },
  {
    id: 3,
    name: "The Place We Always Come To",
    location: "AEON Mall, Deltamas",
    date: "",
    note: "I could go to the same place a thousand times and never get tired of it, as long as I’m with you.",
    emoji: "🛒",
    color: "#f472a8",
    lat: -6.3516,
    lng: 107.1954,
    media: [
      { type: "image", src: "rsc/img/aeon/1.png" },
      { type: "image", src: "rsc/img/aeon/2.png" },
      { type: "image", src: "rsc/img/aeon/3.png" },
      { type: "image", src: "rsc/img/aeon/4.png" },
      { type: "image", src: "rsc/img/aeon/5.png" },
      { type: "image", src: "rsc/img/aeon/6.png" },
      { type: "image", src: "rsc/img/aeon/7.png" },
      { type: "image", src: "rsc/img/aeon/8.png" },
      { type: "image", src: "rsc/img/aeon/9.png" },
      { type: "video", src: "rsc/vid/aeon/1.mp4" },
    ],
  },
  {
    id: 4,
    name: "Your place",
    location: "Semarang",
    date: "",
    note: "Wherever you are is exactly where I feel like I belong.",
    emoji: "🏙️",
    color: "#f472a8",
    lat: -6.966667,
    lng: 110.416664,
    media: [
      { type: "image", src: "rsc/img/smg/1.png" },
      { type: "image", src: "rsc/img/smg/2.png" },
      { type: "image", src: "rsc/img/smg/3.png" },
      { type: "image", src: "rsc/img/smg/4.png" },
      { type: "image", src: "rsc/img/smg/5.png" },
      { type: "image", src: "rsc/img/smg/6.png" },
      { type: "image", src: "rsc/img/smg/7.png" },
      { type: "image", src: "rsc/img/smg/8.png" },
      { type: "image", src: "rsc/img/smg/9.png" },
      { type: "image", src: "rsc/img/smg/10.png" },
      { type: "image", src: "rsc/img/smg/11.png" },
      { type: "image", src: "rsc/img/smg/12.png" },
    ],
  },
  {
    id: 5,
    name: "My Favorite Place",
    location: "Taman Literasi Blok M, Jakarta",
    date: "",
    note: "And then it came to me, through all the days that passed. my heart had never once doubted that you were the one.",
    emoji: "🏕️",
    color: "#f472a8",
    lat: -6.2431,
    lng: 106.7987,
    media: [
      { type: "image", src: "rsc/img/lt-m/1.png" },
      { type: "image", src: "rsc/img/lt-m/2.png" },
      { type: "image", src: "rsc/img/lt-m/3.png" },
      { type: "image", src: "rsc/img/lt-m/4.png" },
      { type: "image", src: "rsc/img/lt-m/5.png" },
      { type: "image", src: "rsc/img/lt-m/6.png" },
      { type: "image", src: "rsc/img/lt-m/7.png" },
      { type: "image", src: "rsc/img/lt-m/8.png" },
      { type: "image", src: "rsc/img/lt-m/9.png" },
      { type: "video", src: "rsc/vid/lt-m/1.mp4" },
    ],
  },
];

