
const places = [
  {
    id: 0,
    name: "Where We First Met",
    location: "BXSea, Tangerang Selatan",
    date: "February 01, 2025",
    note: "",
    emoji: "🐟",
    color: "#f4a0bc",
    lat: -6.2856,
    lng: 106.7289,
    media: [
      { type: "image", src: "rsc/img/dummy.png" },
      { type: "image", src: "rsc/img/dummy.png" },
      { type: "image", src: "rsc/img/dummy.png" },
    ],
  },
  {
    id: 1,
    name: "Our Trip Together",
    location: "Kota Lama, Semarang",
    date: "December 20, 2025",
    note: "",
    emoji: "🏰",
    color: "#f472a8",
    lat: -6.9683,
    lng: 110.4284,
    media: [
      { type: "image", src: "rsc/img/dummy.png" },
      { type: "image", src: "rsc/img/dummy.png" },
      { type: "image", src: "rsc/img/dummy.png" },
    ],
  },
  {
    id: 2,
    name: "We Should Go Here Again",
    location: "Bagi Kopi, Bandung",
    date: "December 20, 2025",
    note: "",
    emoji: "☕",
    color: "#f472a8",
    lat: -6.9456,
    lng: 107.6341,
    media: [
      { type: "image", src: "rsc/img/dummy.png" },
      { type: "image", src: "rsc/img/dummy.png" },
      { type: "image", src: "rsc/img/dummy.png" },
    ],
  },
  {
    id: 3,
    name: "The Place We Always Come To",
    location: "AEON Mall, Deltamas",
    date: "always",
    note: "",
    emoji: "🛒",
    color: "#f472a8",
    lat: -6.3516,
    lng: 107.1954,
    media: [
      { type: "image", src: "rsc/img/dummy.png" },
      { type: "image", src: "rsc/img/dummy.png" },
      { type: "image", src: "rsc/img/dummy.png" },
      // { type: "image", src: "rsc/img/aeon-resource.png" },
    ],
  },
  {
    id: 4,
    name: "My Favorite Place",
    location: "Martha Tiahahu Literacy Park, Jakarta",
    date: "dummy date",
    note: "dummy note",
    emoji: "🏕️",
    color: "#f472a8",
    lat: -6.2431,
    lng: 106.7987,
    media: [
      { type: "image", src: "rsc/img/dummy.png" },
      { type: "image", src: "rsc/img/dummy.png" },
    ],
  },
];
